class LimitStringColumns < ActiveRecord::Migration

  def self.up
    change_column(:assets, :content_type, :string, limit: 255)
    change_column(:assets, :filename, :string, limit: 255)
    change_column(:assets, :thumbnail, :string, limit: 255)
    change_column(:assignments, :subject_type, :string, limit: 255)
    change_column(:elements, :category, :string, limit: 255)
    change_column(:elements, :name, :string, limit: 255)
    change_column(:elements, :display_name, :string, limit: 255)
    change_column(:external_stores, :name, :string, limit: 255)
    change_column(:external_stores, :store_type, :string, limit: 255)
    change_column(:external_targets, :target_type, :string, limit: 255)
    change_column(:external_targets, :name, :string, limit: 255)
    change_column(:external_targets, :value, :string, limit: 255)
    change_column(:item_types, :title_query, :string, limit: 255)
    change_column(:items, :title, :string, limit: 255)
    change_column(:logs, :classification, :string, limit: 255)
    change_column(:logs, :loggable_type, :string, limit: 255)
    change_column(:mapping_instructions, :category, :string, limit: 255)
    change_column(:mapping_item_types, :code, :string, limit: 255)
    change_column(:mapping_templates, :name, :string, limit: 255)
    change_column(:mappings, :name, :string, limit: 255)
    change_column(:mappings, :store_type, :string, limit: 255)
    change_column(:options, :entity_type, :string, limit: 255)
    change_column(:options, :name, :string, limit: 255)
    change_column(:permissions, :permissible_type, :string, limit: 255)
    change_column(:roles, :context_type, :string, limit: 255)
    change_column(:roles, :context_id, :string, limit: 255)
    change_column(:sessions, :session_id, :string, limit: 255)
    change_column(:spaces, :name, :string, limit: 255)
    change_column(:spaces, :workflow_create_role, :string, limit: 255)
    change_column(:verification_sets, :name, :string, limit: 255)
    change_column(:verification_tests, :category, :string, limit: 255)
    change_column(:verification_tests, :query, :string, limit: 255)
    change_column(:verification_tests, :value, :string, limit: 255)
    change_column(:verification_tests, :message, :string, limit: 255)
    change_column(:vocabularies, :name, :string, limit: 255)
    change_column(:vocabulary_members, :name, :string, limit: 255)
    change_column(:vocabulary_members, :value, :string, limit: 255)
    # indexes
    add_index "logs", ["loggable_type", "loggable_id", "classification"], name: "by_loggable_and_classification"
    add_index "options", ["entity_type", "entity_id", "name"], name: "by_entity_and_name"
    add_index "roles", ["context_type", "context_id", "name"], name: "index_roles_on_context_type_and_context_id_and_name", unique: true
    add_index "roles", ["context_type", "name"], name: "index_roles_on_context_type_and_name"
  end

  def self.down
    change_column(:assets, :content_type, :string, limit: nil)
    change_column(:assets, :filename, :string, limit: nil)
    change_column(:assets, :thumbnail, :string, limit: nil)
    change_column(:assignments, :subject_type, :string, limit: nil)
    change_column(:elements, :category, :string, limit: nil)
    change_column(:elements, :name, :string, limit: nil)
    change_column(:elements, :display_name, :string, limit: nil)
    change_column(:external_stores, :name, :string, limit: nil)
    change_column(:external_stores, :store_type, :string, limit: nil)
    change_column(:external_targets, :target_type, :string, limit: nil)
    change_column(:external_targets, :name, :string, limit: nil)
    change_column(:external_targets, :value, :string, limit: nil)
    change_column(:item_types, :title_query, :string, limit: nil)
    change_column(:items, :title, :string, limit: nil)
    change_column(:logs, :classification, :string, limit: nil)
    change_column(:logs, :loggable_type, :string, limit: nil)
    change_column(:mapping_instructions, :category, :string, limit: nil)
    change_column(:mapping_item_types, :code, :string, limit: nil)
    change_column(:mapping_templates, :name, :string, limit: nil)
    change_column(:mappings, :name, :string, limit: nil)
    change_column(:mappings, :store_type, :string, limit: nil)
    change_column(:options, :entity_type, :string, limit: nil)
    change_column(:options, :name, :string, limit: nil)
    change_column(:permissions, :permissible_type, :string, limit: nil)
    change_column(:roles, :context_type, :string, limit: nil)
    change_column(:roles, :context_id, :string, limit: nil)
    change_column(:sessions, :session_id, :string, limit: nil)
    change_column(:spaces, :name, :string, limit: nil)
    change_column(:spaces, :workflow_create_role, :string, limit: nil)
    change_column(:verification_sets, :name, :string, limit: nil)
    change_column(:verification_tests, :category, :string, limit: nil)
    change_column(:verification_tests, :query, :string, limit: nil)
    change_column(:verification_tests, :value, :string, limit: nil)
    change_column(:verification_tests, :message, :string, limit: nil)
    change_column(:vocabularies, :name, :string, limit: nil)
    change_column(:vocabulary_members, :name, :string, limit: nil)
    change_column(:vocabulary_members, :value, :string, limit: nil)
  end
end
